#!/usr/bin/env bash
#
# Generate the SBOM, dependency inventory, and license inventory.
#
# Everything is produced from the currently installed Python environment, which CI
# installs with `pip install --require-hashes -r requirements/dev.txt`. That is what ties
# the SBOM to the lockfile: the SBOM describes the artifacts whose hashes pip verified,
# so the two cannot drift apart.
#
# Nothing is uploaded. No telemetry is emitted. No document is processed. The only
# network access is whatever pip already performed to install the environment; this
# script itself reads the local site-packages metadata.

set -euo pipefail

repo_root="$(git rev-parse --show-toplevel)"
cd "${repo_root}"

out_dir="sbom"
mkdir -p "${out_dir}"

echo "==> CycloneDX SBOM (from the installed environment)"
# --output-reproducible drops timestamps and random serial numbers, so re-running this
# on an unchanged environment produces a byte-identical SBOM.
cyclonedx-py environment \
  --output-format JSON \
  --spec-version 1.6 \
  --output-reproducible \
  --pyproject pyproject.toml \
  --mc-type application \
  --output-file "${out_dir}/oic-python.cdx.json" \
  "$(command -v python)"

echo "==> License inventory"
pip-licenses \
  --format=json \
  --with-authors \
  --with-urls \
  --with-license-file \
  --no-license-path \
  --output-file "${out_dir}/LICENSES.json"

echo "==> Dependency inventory"
{
  echo "# Dependency Inventory"
  echo
  echo "Generated by \`scripts/generate_sbom.sh\` from the installed environment."
  echo "Do not edit by hand. Regenerate after changing \`requirements/*.in\`."
  echo
  echo "The repository itself carries **no license**. Licensing is pending counsel"
  echo "review (see \`OWNERS.md\`). The licenses listed below are those of third-party"
  echo "dependencies and are recorded for inventory purposes only; no compatibility"
  echo "determination has been made."
  echo
  echo "## Environment"
  echo
  echo "- Python: \`$(python --version 2>&1)\`"
  echo "- Platform: \`$(python -c 'import platform; print(platform.platform())')\`"
  echo "- Lockfile: \`requirements/dev.txt\` (hash-pinned, installed with \`--require-hashes\`)"
  echo
  echo "## Installed packages"
  echo
  echo "| Package | Version | License |"
  echo "|---|---|---|"
  python - <<'PY'
import json
import pathlib

data = json.loads(pathlib.Path("sbom/LICENSES.json").read_text(encoding="utf-8"))
for entry in sorted(data, key=lambda item: item["Name"].lower()):
    name = entry["Name"]
    version = entry["Version"]
    license_name = entry.get("License") or "UNKNOWN"
    print(f"| `{name}` | `{version}` | {license_name} |")
PY
  echo
  echo "## Direct requirements"
  echo
  echo '```'
  grep -v -E '^\s*(#|$)' requirements/runtime.in requirements/dev.in || true
  echo '```'
} > "${out_dir}/DEPENDENCY_INVENTORY.md"

echo
echo "Wrote:"
echo "  ${out_dir}/oic-python.cdx.json"
echo "  ${out_dir}/LICENSES.json"
echo "  ${out_dir}/DEPENDENCY_INVENTORY.md"
