#!/usr/bin/env bash
#
# Generate the SBOM, dependency inventory, and license inventory.
#
# Everything is produced from the currently installed Python environment, which CI
# installs with `pip install --require-hashes -r requirements/dev.txt`. That is what ties
# the SBOM to the lockfile: the SBOM describes the artifacts whose hashes pip verified,
# so the two cannot drift apart.
#
# Nothing is uploaded. No telemetry is emitted. No document is processed. The only
# network access is whatever pip already performed to install the environment; this
# script itself reads the local site-packages metadata.

set -euo pipefail

repo_root="$(git rev-parse --show-toplevel)"
cd "${repo_root}"

out_dir="sbom"
mkdir -p "${out_dir}"

echo "==> CycloneDX SBOM (from the installed environment)"
# --output-reproducible drops timestamps and random serial numbers, so re-running this
# on an unchanged environment produces a byte-identical SBOM.
cyclonedx-py environment \
  --output-format JSON \
  --spec-version 1.6 \
  --output-reproducible \
  --pyproject pyproject.toml \
  --mc-type application \
  --output-file "${out_dir}/oic-python.cdx.json" \
  "$(command -v python)"

# cyclonedx records the pyproject location as an absolute `file://` URL, which both
# leaks the generating machine's directory layout and makes the SBOM differ between a
# developer's checkout and CI. Rewrite it to a repository-relative form so the output is
# byte-identical everywhere.
python - "${repo_root}" "${out_dir}/oic-python.cdx.json" <<'PY'
import json
import pathlib
import sys

repo_root, sbom_path = sys.argv[1], pathlib.Path(sys.argv[2])
absolute = f"file://{repo_root}"


def normalise(node: object) -> object:
    if isinstance(node, dict):
        return {key: normalise(value) for key, value in node.items()}
    if isinstance(node, list):
        return [normalise(item) for item in node]
    if isinstance(node, str) and node.startswith(absolute):
        return "file://." + node[len(absolute) :]
    return node


document = json.loads(sbom_path.read_text(encoding="utf-8"))
sbom_path.write_text(
    json.dumps(normalise(document), indent=2, sort_keys=True) + "\n", encoding="utf-8"
)
PY

echo "==> License inventory"
# --with-license-file is deliberately omitted. pip-licenses misidentifies a compiled
# module as the license file for at least one dependency, embedding binary content and
# the generating machine's absolute paths into the output. That is both junk data and a
# path leak in a committed artifact. The declared license name is what the inventory
# needs; full third-party license texts belong in a separate compatibility review.
pip-licenses \
  --format=json \
  --with-authors \
  --with-urls \
  --output-file "${out_dir}/LICENSES.json"

echo "==> Dependency inventory"
{
  echo "# Dependency Inventory"
  echo
  echo "Generated by \`scripts/generate_sbom.sh\` from the installed environment."
  echo "Do not edit by hand. Regenerate after changing \`requirements/*.in\`."
  echo
  echo "The repository is licensed under the PolyForm Noncommercial License 1.0.0."
  echo "Commercial use requires a separate written license from Veraxis. The licenses"
  echo "listed below are those of third-party"
  echo "dependencies and are recorded for inventory purposes only; no compatibility"
  echo "determination has been made."
  echo
  echo "## Environment"
  echo
  echo "- Python: \`$(python --version 2>&1)\`"
  echo "- Platform: \`$(python -c 'import platform; print(platform.platform())')\`"
  echo "- Lockfile: \`requirements/dev.txt\` (hash-pinned, installed with \`--require-hashes\`)"
  echo
  echo "## Installed packages"
  echo
  echo "| Package | Version | License |"
  echo "|---|---|---|"
  python - <<'PY'
import json
import pathlib

data = json.loads(pathlib.Path("sbom/LICENSES.json").read_text(encoding="utf-8"))
for entry in sorted(data, key=lambda item: item["Name"].lower()):
    name = entry["Name"]
    version = entry["Version"]
    license_name = entry.get("License") or "UNKNOWN"
    print(f"| `{name}` | `{version}` | {license_name} |")
PY
  echo
  echo "## Direct requirements"
  echo
  echo '```'
  grep -v -E '^\s*(#|$)' requirements/runtime.in requirements/dev.in || true
  echo '```'
} > "${out_dir}/DEPENDENCY_INVENTORY.md"

echo
echo "Wrote:"
echo "  ${out_dir}/oic-python.cdx.json"
echo "  ${out_dir}/LICENSES.json"
echo "  ${out_dir}/DEPENDENCY_INVENTORY.md"
